[package]
name = "tdx-logger"
version = "0.1.0"
authors = ["Jiewen Yao <jiewen.yao@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tdx-tdcall = { path = "../tdx-tdcall" }
spin = "0.5.2"
log = "0.4.13"
