on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

name: RUN CODE

env:
  RUST_TOOLCHAIN: nightly-2021-08-20
  TOOLCHAIN_PROFILE: minimal

jobs:
  ubuntu:
    name: ubuntu complie
    runs-on: ubuntu-latest
    steps:
      - name: install NASM
        uses: ilammy/setup-nasm@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: rust-src

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Run cargo install cargo-xbuild
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-xbuild

      - name: Build TdShim
        uses: actions-rs/cargo@v1
        env:
          CC: clang
          AR: llvm-ar
        with:
          command: xbuild
          args: -p rust-tdshim --target x86_64-unknown-uefi --release

      - name: Build PE format payload
        run: |
          pushd rust-td-payload
          cargo xbuild --target x86_64-unknown-uefi --release
          popd
          cargo run -p rust-td-tool -- target/x86_64-unknown-uefi/release/ResetVector.bin target/x86_64-unknown-uefi/release/rust-tdshim.efi target/x86_64-unknown-uefi/release/rust-td-payload.efi target/x86_64-unknown-uefi/release/final.bin

      - name: Build Elf format payload
        run: |
          pushd rust-td-payload
          cargo xbuild --target target.json --release
          popd
          cargo run -p rust-td-tool -- target/x86_64-unknown-uefi/release/ResetVector.bin target/x86_64-unknown-uefi/release/rust-tdshim.efi target/target//release/rust-td-payload target/x86_64-unknown-uefi/release/final.bin

  windows:
    name: windows complie
    runs-on: windows-latest
    steps:
      - name: install NASM
        uses: ilammy/setup-nasm@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: rust-src

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Run cargo install cargo-xbuild
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-xbuild

      - name: Build TdShim
        uses: actions-rs/cargo@v1
        env:
          CC: clang
          AR: llvm-ar
        with:
          command: xbuild
          args: -p rust-tdshim --target x86_64-unknown-uefi --release

      - name: Build PE format payload
        run: |
          pushd rust-td-payload
          cargo xbuild --target x86_64-unknown-uefi --release
          popd
          cargo run -p rust-td-tool -- target/x86_64-unknown-uefi/release/ResetVector.bin target/x86_64-unknown-uefi/release/rust-tdshim.efi target/x86_64-unknown-uefi/release/rust-td-payload.efi target/x86_64-unknown-uefi/release/final.bin

      - name: Build Elf format payload
        run: |
          pushd rust-td-payload
          cargo xbuild --target target.json --release
          popd
          cargo run -p rust-td-tool -- target/x86_64-unknown-uefi/release/ResetVector.bin target/x86_64-unknown-uefi/release/rust-tdshim.efi target/target//release/rust-td-payload target/x86_64-unknown-uefi/release/final.bin